# These are supported funding model platforms

ko_fi: tareku
# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# github: tareku
# Replace with up to 4 Patreon usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# Replace with up to 4 Open Collective usernames e.g., [user1, user2]
# open_collective: # Replace with a single Open Collective username
# Replace with up to 4 Community Bridge usernames e.g., [user1, user2]
# community_bridge: # Replace with a single Community Bridge username
# Replace with up to 4 Liberapay usernames e.g., [user1, user2]
# liberapay: # Replace with a single Liberapay username
# Replace with up to 4 IssueHunt usernames e.g., [user1, user2]
# issuehunt: # Replace with a single IssueHunt username
# Replace with up to 4 Otechie usernames e.g., [user1, user2]
# otechie: # Replace with a single Otechie username
# Replace with up to 4 LFX Mentorship (formerly Community Bridge) usernames e.g., [user1, user2]
# lfx_crowdfunding: # Replace with a single LFX Mentorship (formerly Community Bridge) username
# Replace with up to 4 Polar usernames e.g., [user1, user2]
# polar: # Replace with a single Polar username
# Replace with up to 4 Buy Me a Coffee usernames e.g., [user1, user2]
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# Replace with up to 4 Thanks.dev usernames e.g., [user1, user2]
# thanks_dev: # Replace with a single Thanks.dev username
# Replace with up to 4 Custom URLs e.g., ['https://keybase.io/user1', 'https://www.paypal.com/paypalme/user1']
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
